stockpred/stockpred/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stocks', include('stocks.urls'))
]

stockpred/stocks/urls.py
from django.urls import path
from . import views

app_name = "stocks"
urlpatterns = [
    path('', views.index, name="index"),
]

stockpred/stocks/models.py
from django.db import models

# Create your models here.

stockpred/stocks/views.py
from django.shortcuts import render
from .stock_model import *
import pickle

# Create your views here.
def index(request):

    if request.method == 'POST':
        sname = request.POST['search']

        data, d = DataImport(sname)

        OneYear_data(data)

        LastMonth_data(data)

        LastWeek_data(data)

        model, scaler = modelBuilding(data)

        pred, next_data = predictData(data, d, model, scaler)

        data_final = CombineData(data, pred, next_data)

        plotPredict(data_final, sname)


        return render(request, 'stocks/index.html', {
            "disp": True,
        })

    return render(request, 'stocks/index.html', {
        "disp": False,
    })

stockpred/stocks/templates/stocks/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Buddy</title>
    <link rel="stylesheet" href="{% static 'stocks/index.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
</head>
<body>
    <div class="allabove">
    <div class="header"> 
        <div class="uparkamala">
                <div class="logoo">
                    <a href= "#">
                        <img src="{% static 'images/loralogo.png' %}" alt="meralora">
                    </a>
                </div>
                <div class="navbar">
                    <nav>
                        <ul>
                            <li class="right-items"><a href="#">About</a>
                                
                            </li>
                            <li class="right-items"><a href="#">Services</a>
                                
                            </li>
                            <li class="right-items"><a href="#">Contact</a>
                                
                            </li>
                            <li class="right-items" id="home">
                                <a href="{% url 'stocks:index' %}">Home</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            </div>
        </div>
            <div class="search-container">
                <form method="post">
                    {% csrf_token %}
                    <input type="search" placeholder="Enter a company.." name="search" id="search">
                    <button type="submit">
                        <span class="material-symbols-outlined white-icon">query_stats</span>
                    </button>
                </form>
            </div>
            <div class="imagegrid"> 
                {% if disp %}
                    <div>
                        <img src="{% static 'images/fullStock.png' %}" alt="logo">
                    </div>
                    <div>
                        <img src="{% static 'images/yearly.png' %}" style="position: relative; width: 500px; left: -150px;">
                    </div>
                    <div>
                        <img src="{% static 'images/monthly.png' %}" style="position: relative; width: 500px; left: -50px;">
                    </div>
                    <div>
                        <img src="{% static 'images/weekly.png' %}" style="position: relative; width: 500px; left: -150px;">
                    </div>
                    <div>
                        <img src="{% static 'images/Data_Prediction.png' %}" style="position: relative; width: 500px; left: -50px;">
                    </div>
                {% endif %}
            </div>
            <!-- <div class="imagecontainer">
                <div id="analytics1">
                        <img src="image1.jpg" alt="logo">
                </div>
                <div id="analytics2">
                    <img src="image2.jpg" alt="">
                </div>
                <div id="analytics3">
                    <img src="image3.jpg" alt="">
                </div>
                <div id="analytics4">
                    <img src="image4.jpg" alt="">
                </div>
                <div id="analytics5">
                    <img src="codeeeee.jpg" alt="">
                </div>
            </div> -->

    <script>
        // Add an event listener to the search button instead of the form submission
        document.getElementById("searchButton").addEventListener("click", function() {
            var searchInputValue = document.getElementById("searchInput").value;
            // Here you can perform the search action with the searchInputValue
            // For example, redirect to a search results page or perform an AJAX request
            console.log("Search query: " + searchInputValue);
        });

        document.addEventListener("DOMContentLoaded", function() {
            const searchForm = document.getElementById("searchForm");
            const imageContainer = document.getElementById("imageContainer");

            searchForm.addEventListener("submit", function(event) {
                event.preventDefault(); // Prevent default form submission

                // Scroll the page to the image container
                imageContainer.scrollIntoView({ behavior: "smooth" });

                // Show all images in the image container
                imageContainer.style.display = "flex";
            });
        });

        window.addEventListener('scroll', function() {
            var header = document.getElementById('header');
            if (window.scrollY > 0) {
                header.classList.add('scroll');
            } else {
                header.classList.remove('scroll');
            }
        });
    </script>


</body>
</html>




 